apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: star_wars
  template:
    metadata:
      labels:
        app: star_wars
        version: 1.0
    spec:
      containers:
      - name: django-app
        image: luctabla/star_wars_web:firsttry
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: djando-env
        ports:
        - containerPort: 8000
          name: daphne
      - name: redis
        image: redis:5
        ports:
        - containerPort: 6379
          name: redis
      imagePullSecrets:
      - name: regcred

